language: csharp

addons:
  apt:
    packages:
       - msbuild

sudo: false # use the new container-based Travis infrastructure
dist: trusty # Ubuntu 14.04
dotnet: 2.1

script:
  - dotnet --info
  - dotnet tool install fake-cli -g 
  - fake run build.fsx target RunTests
